# Task
Implement four Python functions:
1.  **Smart Parking Lot Management System**: A function to manage a smart parking lot. It should accept parking capacity and a list of vehicle entry/exit logs, then calculate the current number of parked vehicles and determine the parking status (available or full).
2.  **Online Food Delivery Time Estimator**: A function to estimate food delivery time. It should take distance (km), traffic level ('Low', 'Medium', 'High'), and weather condition ('Clear', 'Rainy', 'Snowy') as inputs, apply dynamic delays, and output the estimated total delivery time in minutes.
3.  **Movie Theatre Seat Occupancy Analyzer**: A function to analyze movie theatre seat booking data. It should accept the total number of seats and a list of booked seats, then calculate the occupancy percentage and determine the show's status ('Available', 'Almost Full', or 'Housefull').
4.  **Cloud Server Load Classification System**: A function to classify cloud server load. It should take a list of CPU usage percentages, calculate the average CPU load, and classify the server status as 'Normal' (<50%), 'Warning' (50-80%), or 'Critical' (>80%).

After implementing these functions, review and summarize their implementations, confirming they meet requirements and provide expected outputs for the specified sample inputs.

## Smart Parking Lot Management System

### Subtask:
Design and implement a Python function to manage a smart parking lot. This function will accept parking capacity and a list of vehicle entry/exit logs as input. It will calculate the current number of parked vehicles, determine the parking status (available or full based on capacity), and return these details. The function will be tested with the provided sample input: Capacity: 50, Logs: ["IN", "IN", "IN", "OUT", "IN", "IN", "OUT"].


**Reasoning**:
The subtask requires defining a Python function to manage a smart parking lot, processing entry/exit logs, and determining the parking status. This code block will implement the function and test it with the provided sample input.



In [1]:
def smart_parking_lot_management(capacity, logs):
    """
    Manages a smart parking lot, calculating current parked vehicles and status.

    Args:
        capacity (int): The total capacity of the parking lot.
        logs (list): A list of strings, each being 'IN' for entry or 'OUT' for exit.

    Returns:
        dict: A dictionary containing 'parked_vehicles' (int) and 'parking_status' (str).
    """
    parked_vehicles = 0
    for log in logs:
        if log == 'IN':
            parked_vehicles += 1
        elif log == 'OUT':
            # Ensure parked_vehicles does not go below zero
            parked_vehicles = max(0, parked_vehicles - 1)

    parking_status = 'Full' if parked_vehicles >= capacity else 'Available'

    return {
        'parked_vehicles': parked_vehicles,
        'parking_status': parking_status
    }

# Sample input
capacity_sample = 50
logs_sample = ["IN", "IN", "IN", "OUT", "IN", "IN", "OUT"]

# Call the function with sample input
result = smart_parking_lot_management(capacity_sample, logs_sample)

# Print the returned values
print(f"Current Parked Vehicles: {result['parked_vehicles']}")
print(f"Parking Status: {result['parking_status']}")

Current Parked Vehicles: 3
Parking Status: Available


## Online Food Delivery Time Estimator

### Subtask:
Create a Python function that estimates food delivery time. The function will take distance (km), traffic level (e.g., 'Low', 'Medium', 'High'), and weather condition (e.g., 'Clear', 'Rainy', 'Snowy') as inputs. It will apply dynamic delays based on these conditions and output the estimated total delivery time in minutes. The function will be tested with the sample input: Distance: 8 km, Traffic Level: High, Weather: Rainy.


**Reasoning**:
The subtask requires implementing the `online_food_delivery_time_estimator` function with specific logic for calculating delivery time and applying dynamic delays based on traffic and weather. I will write the Python code for this function, call it with the provided sample inputs, and then print the estimated delivery time.



In [2]:
def online_food_delivery_time_estimator(distance_km, traffic_level, weather_condition):
    """
    Estimates food delivery time based on distance, traffic, and weather conditions.

    Args:
        distance_km (float): The delivery distance in kilometers.
        traffic_level (str): The current traffic level ('Low', 'Medium', 'High').
        weather_condition (str): The current weather condition ('Clear', 'Rainy', 'Snowy').

    Returns:
        float: The estimated total delivery time in minutes.
    """
    # Base delivery time (e.g., 5 minutes per km)
    base_delivery_time = distance_km * 5
    total_delivery_time = base_delivery_time

    # Apply delays based on traffic level
    if traffic_level == 'Medium':
        total_delivery_time += base_delivery_time * 0.10  # 10% delay
    elif traffic_level == 'High':
        total_delivery_time += base_delivery_time * 0.25  # 25% delay
    # 'Low' traffic adds 0 minutes, so no action needed

    # Apply delays based on weather condition
    if weather_condition == 'Rainy':
        total_delivery_time += base_delivery_time * 0.15  # 15% delay
    elif weather_condition == 'Snowy':
        total_delivery_time += base_delivery_time * 0.30  # 30% delay
    # 'Clear' weather adds 0 minutes, so no action needed

    return total_delivery_time

# Sample input
distance_km_sample = 8
traffic_level_sample = 'High'
weather_condition_sample = 'Rainy'

# Call the function with sample input
estimated_time = online_food_delivery_time_estimator(
    distance_km_sample,
    traffic_level_sample,
    weather_condition_sample
)

# Print the returned estimated delivery time
print(f"Estimated Food Delivery Time: {estimated_time:.2f} minutes")

Estimated Food Delivery Time: 56.00 minutes


## Movie Theatre Seat Occupancy Analyzer

### Subtask:
Develop a Python function to analyze movie theatre seat booking data. This function will accept the total number of seats and a list of booked seats as input. It will calculate the occupancy percentage and determine the show's status (e.g., 'Available', 'Almost Full', 'Housefull'). The function will be tested with the provided sample input: Total Seats: 200, Booked Seats: [1,1,1,1,1,1,1,1,1,1] (150 entries).


**Reasoning**:
The subtask requires implementing a Python function to analyze movie theatre seat occupancy. I will define the function as specified, calculate the occupied seats, occupancy percentage, and determine the show status. Then, I will test it with the given sample input and print the results.



In [3]:
def movie_theatre_seat_occupancy_analyzer(total_seats, booked_seats):
    """
    Analyzes movie theatre seat booking data to determine occupancy and show status.

    Args:
        total_seats (int): The total number of seats in the theatre.
        booked_seats (list): A list of booked seat numbers.

    Returns:
        dict: A dictionary containing 'occupied_seats_count', 'occupancy_percentage', and 'show_status'.
    """
    # Calculate the number of unique booked seats
    # Using a set to handle potential duplicate entries in booked_seats if they were not unique seat IDs
    occupied_seats_count = len(set(booked_seats))

    # Ensure occupied_seats_count does not exceed total_seats
    occupied_seats_count = min(occupied_seats_count, total_seats)

    # Calculate occupancy percentage
    occupancy_percentage = (occupied_seats_count / total_seats) * 100

    # Determine show status
    if occupancy_percentage == 100:
        show_status = 'Housefull'
    elif occupancy_percentage >= 80:
        show_status = 'Almost Full'
    else:
        show_status = 'Available'

    return {
        'occupied_seats_count': occupied_seats_count,
        'occupancy_percentage': occupancy_percentage,
        'show_status': show_status
    }

# Sample input
total_seats_sample = 200
# The instruction specifies 150 entries, using [1] * 150 to create a list of 150 booked seats.
# Note: If the intention was 150 *unique* booked seats, the input format would need to change.
# For now, assuming the list itself has 150 entries, and `len(set(booked_seats))` will correctly count unique ones.
# In this specific sample, len(set([1]*150)) would be 1.
# To match the spirit of '150 entries' implying 150 *occupied* seats, I'll create 150 distinct booked seat numbers.
booked_seats_sample = list(range(1, 151)) # This creates 150 unique booked seats from 1 to 150

# Call the function with sample input
result = movie_theatre_seat_occupancy_analyzer(total_seats_sample, booked_seats_sample)

# Print the returned values
print(f"Occupied Seats Count: {result['occupied_seats_count']}")
print(f"Occupancy Percentage: {result['occupancy_percentage']:.2f}%")
print(f"Show Status: {result['show_status']}")

Occupied Seats Count: 150
Occupancy Percentage: 75.00%
Show Status: Available


### Movie Theatre Seat Occupancy Analyzer - Summary

The `movie_theatre_seat_occupancy_analyzer` function has been successfully implemented and tested. It accurately calculates the `occupied_seats_count` by taking the length of unique `booked_seats` (using a set to handle potential duplicates), calculates the `occupancy_percentage`, and assigns a `show_status` ('Housefull', 'Almost Full', or 'Available') based on the percentage thresholds.

For the provided sample input:
- **Total Seats:** 200
- **Booked Seats:** 150 unique seats (generated using `list(range(1, 151))`) as implied by '150 entries'.

The function correctly returned:
- **Occupied Seats Count:** 150
- **Occupancy Percentage:** 75.00%
- **Show Status:** 'Available'

This output confirms that the function meets all the specified requirements for calculating occupancy and determining the show status.

### Movie Theatre Seat Occupancy Analyzer - Summary

The `movie_theatre_seat_occupancy_analyzer` function has been successfully implemented and tested. It accurately calculates the `occupied_seats_count` by taking the length of unique `booked_seats` (using a set to handle potential duplicates), calculates the `occupancy_percentage`, and assigns a `show_status` ('Housefull', 'Almost Full', or 'Available') based on the percentage thresholds.

For the provided sample input:
- **Total Seats:** 200
- **Booked Seats:** 150 unique seats (generated using `list(range(1, 151))`) as implied by '150 entries'.

The function correctly returned:
- **Occupied Seats Count:** 150
- **Occupancy Percentage:** 75.00%
- **Show Status:** 'Available'

This output confirms that the function meets all the specified requirements for calculating occupancy and determining the show status.

### Movie Theatre Seat Occupancy Analyzer - Summary

The `movie_theatre_seat_occupancy_analyzer` function has been successfully implemented and tested. It accurately calculates the `occupied_seats_count` by taking the length of unique `booked_seats` (using a set to handle potential duplicates), calculates the `occupancy_percentage`, and assigns a `show_status` ('Housefull', 'Almost Full', or 'Available') based on the percentage thresholds.

For the provided sample input:
- **Total Seats:** 200
- **Booked Seats:** 150 unique seats (generated using `list(range(1, 151))`) as implied by '150 entries'.

The function correctly returned:
- **Occupied Seats Count:** 150
- **Occupancy Percentage:** 75.00%
- **Show Status:** 'Available'

This output confirms that the function meets all the specified requirements for calculating occupancy and determining the show status.

## Cloud Server Load Classification System

### Subtask:
Design and implement a Python function to classify cloud server load. This function should take a list of CPU usage percentages as input, calculate the average CPU load, and then classify the server status as 'Normal' (<50%), 'Warning' (50-80%), or 'Critical' (>80%). The function will be tested with the provided sample input: CPU Usage Percentages: [45, 55, 60, 75, 40, 85, 90, 65].

## Cloud Server Load Classification System

### Subtask:
Design and implement a Python function to classify cloud server load. This function should take a list of CPU usage percentages as input, calculate the average CPU load, and then classify the server status as 'Normal' (<50%), 'Warning' (50-80%), or 'Critical' (>80%). The function will be tested with the provided sample input: CPU Usage Percentages: [45, 55, 60, 75, 40, 85, 90, 65].

#### Instructions
1. Define a Python function `cloud_server_load_classifier` that takes a list of `cpu_usage_percentages` (a list of integers) as input.
2. Inside the function, calculate the `average_cpu_load` from the given list.
3. Classify the `server_status` based on the `average_cpu_load`:
    - If `average_cpu_load` is less than 50%, the status is 'Normal'.
    - If `average_cpu_load` is between 50% (inclusive) and 80% (inclusive), the status is 'Warning'.
    - If `average_cpu_load` is greater than 80%, the status is 'Critical'.
4. The function should return a dictionary containing `average_cpu_load` and `server_status`.
5. Prepare the sample input: `cpu_usage_sample = [45, 55, 60, 75, 40, 85, 90, 65]`.
6. Call the `cloud_server_load_classifier` function with the sample input.
7. Print the returned `average_cpu_load` and `server_status` in a clear and readable format.

**Reasoning**:
The subtask requires implementing the `cloud_server_load_classifier` function to calculate the average CPU load from a list of percentages and then classify the server's status based on predefined thresholds. This code block will implement the function and test it with the provided sample input.

**Reasoning**:
The previous markdown block provided the instructions and reasoning for the 'Cloud Server Load Classification System' subtask. Now, I will implement the Python function `cloud_server_load_classifier` as described, calculate the average CPU load, classify the server status, and test it with the provided sample input.



In [4]:
def cloud_server_load_classifier(cpu_usage_percentages):
    """
    Classifies cloud server load based on a list of CPU usage percentages.

    Args:
        cpu_usage_percentages (list): A list of integer CPU usage percentages.

    Returns:
        dict: A dictionary containing 'average_cpu_load' (float) and 'server_status' (str).
    """
    if not cpu_usage_percentages:
        return {
            'average_cpu_load': 0.0,
            'server_status': 'Normal' # Assuming 0 usage is Normal
        }

    average_cpu_load = sum(cpu_usage_percentages) / len(cpu_usage_percentages)

    if average_cpu_load < 50:
        server_status = 'Normal'
    elif 50 <= average_cpu_load <= 80:
        server_status = 'Warning'
    else:  # average_cpu_load > 80
        server_status = 'Critical'

    return {
        'average_cpu_load': average_cpu_load,
        'server_status': server_status
    }

# Sample input
cpu_usage_sample = [45, 55, 60, 75, 40, 85, 90, 65]

# Call the function with sample input
result = cloud_server_load_classifier(cpu_usage_sample)

# Print the returned values
print(f"Average CPU Load: {result['average_cpu_load']:.2f}%")
print(f"Server Status: {result['server_status']}")

Average CPU Load: 64.38%
Server Status: Warning


### Cloud Server Load Classification System - Summary

The `cloud_server_load_classifier` function has been successfully implemented and tested. It accurately calculates the `average_cpu_load` from a list of `cpu_usage_percentages` and then classifies the `server_status` as 'Normal', 'Warning', or 'Critical' based on the specified thresholds.

For the provided sample input:
- **CPU Usage Percentages:** `[45, 55, 60, 75, 40, 85, 90, 65]`

The function correctly returned:
- **Average CPU Load:** 64.38%
- **Server Status:** 'Warning'

This output confirms that the function meets all the specified requirements for calculating average CPU load and determining the server status.

### Cloud Server Load Classification System - Summary

The `cloud_server_load_classifier` function has been successfully implemented and tested. It accurately calculates the `average_cpu_load` from a list of `cpu_usage_percentages` and then classifies the `server_status` as 'Normal', 'Warning', or 'Critical' based on the specified thresholds.

For the provided sample input:
- **CPU Usage Percentages:** `[45, 55, 60, 75, 40, 85, 90, 65]`

The function correctly returned:
- **Average CPU Load:** 64.38%
- **Server Status:** 'Warning'

This output confirms that the function meets all the specified requirements for calculating average CPU load and determining the server status.

## Final Task

### Subtask:
Review and summarize the implementations of all four functions, confirming that they meet the problem requirements and provide the expected outputs for the given sample inputs.


## Summary:

### Data Analysis Key Findings

*   **Smart Parking Lot Management System**: For a parking lot with a capacity of 50 and logs `["IN", "IN", "IN", "OUT", "IN", "IN", "OUT"]`, the current number of parked vehicles is 3, and the parking status is 'Available'.
*   **Online Food Delivery Time Estimator**: For a distance of 8 km, 'High' traffic, and 'Rainy' weather, the estimated delivery time is 56.00 minutes. This includes a base time of 40 minutes (8 km * 5 min/km), a 25% traffic delay (10 minutes), and a 15% weather delay (6 minutes).
*   **Movie Theatre Seat Occupancy Analyzer**: Given 200 total seats and 150 unique booked seats, the occupied seats count is 150, leading to an occupancy percentage of 75.00%. The show status is classified as 'Available'.
*   **Cloud Server Load Classification System**: For CPU usage percentages `[45, 55, 60, 75, 40, 85, 90, 65]`, the average CPU load is 64.38%, classifying the server status as 'Warning'.

### Insights or Next Steps

*   The implemented functions successfully meet their respective problem requirements and accurately process sample inputs, demonstrating robust logic for various real-world scenarios.
*   For future enhancements, consider adding error handling for invalid input types or out-of-range values (e.g., negative capacity, traffic levels other than defined ones) to improve the functions' resilience.


# Task
Implement two Python functions:
1.  **Smart Classroom Resource Usage Monitor**: To track usage of classroom resources (projector, AC, lights) and identify overuse patterns. This function will accept a dictionary of resource usage in hours, define thresholds for overuse (e.g., AC > 8 hours, Projector > 5 hours, Lights > 6 hours), identify which resources are overused, and determine if an 'Energy Alert' is needed. It will be tested with the sample input: {"Projector": 6, "AC": 9, "Lights": 4}.
2.  **Online Event Registration Capacity Controller**: To manage event registrations. This function will take event capacity and the total number of registrations as input. It will calculate the number of confirmed registrations, the number of waitlisted users (if any), and determine the overall registration status ('Open', 'Closed', or 'Waitlist'). It will be tested with the sample input: Event Capacity: 100, Registrations: 105.

After implementing both functions, review and summarize their implementations, confirming they meet the problem requirements and provide the expected outputs for the given sample inputs.

## Smart Classroom Resource Usage Monitor

### Subtask:
Design and implement a Python function to track usage of classroom resources (projector, AC, lights) and identify overuse patterns. The function will accept a dictionary of resource usage in hours, define thresholds for overuse (e.g., AC > 8 hours, Projector > 5 hours, Lights > 6 hours), identify which resources are overused, and determine if an 'Energy Alert' is needed. It will be tested with the sample input: {"Projector": 6, "AC": 9, "Lights": 4}.


**Reasoning**:
The subtask requires implementing the `smart_classroom_resource_monitor` function to track resource usage, identify overused resources based on predefined thresholds, and determine if an 'Energy Alert' is needed. I will write the Python code for this function, call it with the provided sample inputs, and then print the identified overused resources and the energy alert status.

**Reasoning**:
I will implement the `smart_classroom_resource_monitor` function based on the provided instructions. This includes defining thresholds, iterating through resource usage, identifying overused resources, determining the energy alert status, and returning the results. Finally, I will test the function with the given sample input and print the output.



In [5]:
def smart_classroom_resource_monitor(resource_usage):
    """
    Tracks classroom resource usage, identifies overuse patterns, and determines if an 'Energy Alert' is needed.

    Args:
        resource_usage (dict): A dictionary where keys are resource names (str) and
                                values are usage in hours (int or float).

    Returns:
        dict: A dictionary containing:
              - 'overused_resources' (list): A list of resource names that exceed their thresholds.
              - 'energy_alert' (bool): True if any resource is overused, False otherwise.
    """
    # Define overuse thresholds for each resource
    overuse_thresholds = {
        'Projector': 5,
        'AC': 8,
        'Lights': 6
    }

    overused_resources = []

    # Iterate through resource usage to identify overused resources
    for resource, usage in resource_usage.items():
        if resource in overuse_thresholds and usage > overuse_thresholds[resource]:
            overused_resources.append(resource)

    # Determine energy alert status
    energy_alert = bool(overused_resources)

    return {
        'overused_resources': overused_resources,
        'energy_alert': energy_alert
    }

# Sample input
resource_usage_sample = {"Projector": 6, "AC": 9, "Lights": 4}

# Call the function with sample input
result = smart_classroom_resource_monitor(resource_usage_sample)

# Print the returned values
print(f"Overused Resources: {result['overused_resources']}")
print(f"Energy Alert Needed: {result['energy_alert']}")

Overused Resources: ['Projector', 'AC']
Energy Alert Needed: True


### Smart Classroom Resource Usage Monitor - Summary

The `smart_classroom_resource_monitor` function has been successfully implemented and tested. It accurately identifies resources that exceed predefined usage thresholds and determines if an 'Energy Alert' is required.

For the provided sample input:
- **Resource Usage:** `{"Projector": 6, "AC": 9, "Lights": 4}`

The function correctly returned:
- **Overused Resources:** `['Projector', 'AC']`
- **Energy Alert Needed:** `True`

This output confirms that the function meets all the specified requirements for tracking resource usage, identifying overuse patterns, and determining the energy alert status.

## Online Event Registration Capacity Controller

### Subtask:
To manage event registrations. This function will take event capacity and the total number of registrations as input. It will calculate the number of confirmed registrations, the number of waitlisted users (if any), and determine the overall registration status ('Open', 'Closed', or 'Waitlist'). It will be tested with the sample input: Event Capacity: 100, Registrations: 105.

#### Instructions
1. Define a Python function `online_event_registration_controller` that takes `event_capacity` (int) and `total_registrations` (int) as input.
2. Inside the function, calculate `confirmed_registrations`: this should be the minimum of `event_capacity` and `total_registrations`.
3. Calculate `waitlisted_users`: if `total_registrations` exceeds `event_capacity`, this will be the difference; otherwise, it will be 0.
4. Determine the `registration_status` based on these conditions:
    - If `total_registrations` is less than `event_capacity`, the status is 'Open'.
    - If `total_registrations` is equal to `event_capacity`, the status is 'Closed'.
    - If `total_registrations` is greater than `event_capacity`, the status is 'Waitlist'.
5. The function should return a dictionary containing `confirmed_registrations`, `waitlisted_users`, and `registration_status`.
6. Prepare the sample input: `event_capacity_sample = 100`, `total_registrations_sample = 105`.
7. Call the `online_event_registration_controller` function with the sample input.
8. Print the returned values in a clear and readable format.

**Reasoning**:
The subtask requires implementing the `online_event_registration_controller` function to manage event registrations, calculating confirmed registrations, waitlisted users, and determining the overall registration status. This code block will implement the function and test it with the provided sample input.

#### Instructions
1. Define a Python function `online_event_registration_controller` that takes `event_capacity` (int) and `total_registrations` (int) as input.
2. Inside the function, calculate `confirmed_registrations`: this should be the minimum of `event_capacity` and `total_registrations`.
3. Calculate `waitlisted_users`: if `total_registrations` exceeds `event_capacity`, this will be the difference; otherwise, it will be 0.
4. Determine the `registration_status` based on these conditions:
    - If `total_registrations` is less than `event_capacity`, the status is 'Open'.
    - If `total_registrations` is equal to `event_capacity`, the status is 'Closed'.
    - If `total_registrations` is greater than `event_capacity`, the status is 'Waitlist'.
5. The function should return a dictionary containing `confirmed_registrations`, `waitlisted_users`, and `registration_status`.
6. Prepare the sample input: `event_capacity_sample = 100`, `total_registrations_sample = 105`.
7. Call the `online_event_registration_controller` function with the sample input.
8. Print the returned values in a clear and readable format.

**Reasoning**:
The subtask requires implementing the `online_event_registration_controller` function to manage event registrations, calculating confirmed registrations, waitlisted users, and determining the overall registration status. This code block will implement the function and test it with the provided sample input.

#### Instructions
1. Define a Python function `online_event_registration_controller` that takes `event_capacity` (int) and `total_registrations` (int) as input.
2. Inside the function, calculate `confirmed_registrations`: this should be the minimum of `event_capacity` and `total_registrations`.
3. Calculate `waitlisted_users`: if `total_registrations` exceeds `event_capacity`, this will be the difference; otherwise, it will be 0.
4. Determine the `registration_status` based on these conditions:
    - If `total_registrations` is less than `event_capacity`, the status is 'Open'.
    - If `total_registrations` is equal to `event_capacity`, the status is 'Closed'.
    - If `total_registrations` is greater than `event_capacity`, the status is 'Waitlist'.
5. The function should return a dictionary containing `confirmed_registrations`, `waitlisted_users`, and `registration_status`.
6. Prepare the sample input: `event_capacity_sample = 100`, `total_registrations_sample = 105`.
7. Call the `online_event_registration_controller` function with the sample input.
8. Print the returned values in a clear and readable format.

**Reasoning**:
The subtask requires implementing the `online_event_registration_controller` function to manage event registrations, calculating confirmed registrations, waitlisted users, and determining the overall registration status. This code block will implement the function and test it with the provided sample input.

**Reasoning**:
The previous markdown block provided the instructions and reasoning for the 'Online Event Registration Capacity Controller' subtask. Now, I will implement the Python function `online_event_registration_controller` as described, calculate confirmed registrations, waitlisted users, and classify the registration status, then test it with the provided sample input.



In [6]:
def online_event_registration_controller(event_capacity, total_registrations):
    """
    Manages event registrations, calculating confirmed registrations, waitlisted users,
    and determining the overall registration status.

    Args:
        event_capacity (int): The maximum capacity of the event.
        total_registrations (int): The total number of users who have attempted to register.

    Returns:
        dict: A dictionary containing 'confirmed_registrations' (int),
              'waitlisted_users' (int), and 'registration_status' (str).
    """
    confirmed_registrations = min(event_capacity, total_registrations)

    waitlisted_users = max(0, total_registrations - event_capacity)

    if total_registrations < event_capacity:
        registration_status = 'Open'
    elif total_registrations == event_capacity:
        registration_status = 'Closed'
    else:  # total_registrations > event_capacity
        registration_status = 'Waitlist'

    return {
        'confirmed_registrations': confirmed_registrations,
        'waitlisted_users': waitlisted_users,
        'registration_status': registration_status
    }

# Sample input
event_capacity_sample = 100
total_registrations_sample = 105

# Call the function with sample input
result = online_event_registration_controller(event_capacity_sample, total_registrations_sample)

# Print the returned values
print(f"Confirmed Registrations: {result['confirmed_registrations']}")
print(f"Waitlisted Users: {result['waitlisted_users']}")
print(f"Registration Status: {result['registration_status']}")

Confirmed Registrations: 100
Waitlisted Users: 5
Registration Status: Waitlist


### Online Event Registration Capacity Controller - Summary

The `online_event_registration_controller` function has been successfully implemented and tested. It accurately calculates the `confirmed_registrations`, `waitlisted_users`, and determines the `registration_status` based on the event capacity and total registrations.

For the provided sample input:
- **Event Capacity:** 100
- **Total Registrations:** 105

The function correctly returned:
- **Confirmed Registrations:** 100
- **Waitlisted Users:** 5
- **Registration Status:** 'Waitlist'

This output confirms that the function meets all the specified requirements for managing event registrations and determining their status.

### Online Event Registration Capacity Controller - Summary

The `online_event_registration_controller` function has been successfully implemented and tested. It accurately calculates the `confirmed_registrations`, `waitlisted_users`, and determines the `registration_status` based on the event capacity and total registrations.

For the provided sample input:
- **Event Capacity:** 100
- **Total Registrations:** 105

The function correctly returned:
- **Confirmed Registrations:** 100
- **Waitlisted Users:** 5
- **Registration Status:** 'Waitlist'

This output confirms that the function meets all the specified requirements for managing event registrations and determining their status.

### Online Event Registration Capacity Controller - Summary

The `online_event_registration_controller` function has been successfully implemented and tested. It accurately calculates the `confirmed_registrations`, `waitlisted_users`, and determines the `registration_status` based on the event capacity and total registrations.

For the provided sample input:
- **Event Capacity:** 100
- **Total Registrations:** 105

The function correctly returned:
- **Confirmed Registrations:** 100
- **Waitlisted Users:** 5
- **Registration Status:** 'Waitlist'

This output confirms that the function meets all the specified requirements for managing event registrations and determining their status.

## Final Task Summary: Implemented Functions Review

This section reviews the implementations of the two Python functions developed:
1.  **Smart Classroom Resource Usage Monitor**
2.  **Online Event Registration Capacity Controller**

### 1. Smart Classroom Resource Usage Monitor

**Description**: This function tracks classroom resource usage, identifies overuse patterns based on predefined thresholds, and determines if an 'Energy Alert' is needed.

**Implementation Review**:
-   The function `smart_classroom_resource_monitor` correctly accepts a dictionary of resource usage.
-   It defines specific overuse thresholds for 'Projector', 'AC', and 'Lights'.
-   It iterates through the provided usage data, accurately comparing each resource's usage against its threshold.
-   A list of `overused_resources` is generated, containing all resources exceeding their thresholds.
-   The `energy_alert` boolean flag is correctly set to `True` if any resources are overused, and `False` otherwise.

**Sample Input and Output Verification**:
-   **Input**: `resource_usage_sample = {"Projector": 6, "AC": 9, "Lights": 4}`
-   **Expected Output**: `Overused Resources: ['Projector', 'AC']`, `Energy Alert Needed: True`
-   **Actual Output**: The code successfully returned `Overused Resources: ['Projector', 'AC']` and `Energy Alert Needed: True`. This confirms the function's accuracy for the given sample.

### 2. Online Event Registration Capacity Controller

**Description**: This function manages event registrations by calculating confirmed registrations, waitlisted users, and determining the overall registration status ('Open', 'Closed', or 'Waitlist').

**Implementation Review**:
-   The function `online_event_registration_controller` correctly takes `event_capacity` and `total_registrations` as inputs.
-   `confirmed_registrations` is correctly calculated as the minimum of `event_capacity` and `total_registrations`.
-   `waitlisted_users` is accurately determined as the difference between `total_registrations` and `event_capacity` if registrations exceed capacity, otherwise 0.
-   The `registration_status` is correctly assigned based on the comparison between `total_registrations` and `event_capacity` ('Open' if less, 'Closed' if equal, 'Waitlist' if greater).

**Sample Input and Output Verification**:
-   **Input**: `event_capacity_sample = 100`, `total_registrations_sample = 105`
-   **Expected Output**: `Confirmed Registrations: 100`, `Waitlisted Users: 5`, `Registration Status: 'Waitlist'`
-   **Actual Output**: The code successfully returned `Confirmed Registrations: 100`, `Waitlisted Users: 5`, and `Registration Status: 'Waitlist'`. This confirms the function's accuracy for the given sample.

### Conclusion

Both `smart_classroom_resource_monitor` and `online_event_registration_controller` functions have been implemented as per the requirements. They demonstrate robust logic for their respective tasks and provide accurate outputs for the specified sample inputs. All aspects of the main task have been successfully addressed.

## Final Task

### Subtask:
Review and summarize the implementations of both the 'Smart Classroom Resource Usage Monitor' and 'Online Event Registration Capacity Controller' functions, confirming that they meet the problem requirements and provide the expected outputs for the given sample inputs.


## Summary:

### Data Analysis Key Findings

*   The `smart_classroom_resource_monitor` function successfully identified overused resources and determined the energy alert status. For the sample input `{"Projector": 6, "AC": 9, "Lights": 4}` (with thresholds: Projector > 5, AC > 8, Lights > 6), the function correctly returned `['Projector', 'AC']` as overused resources and `True` for an energy alert.
*   The `online_event_registration_controller` function accurately managed event registrations. Given an event capacity of 100 and 105 total registrations, the function correctly calculated 100 confirmed registrations, 5 waitlisted users, and set the registration status to 'Waitlist'.

### Insights or Next Steps

*   **Smart Classroom Resource Usage Monitor**: The current implementation effectively flags individual resources. Future enhancements could include aggregating total energy consumption or suggesting corrective actions for overused resources.
*   **Online Event Registration Capacity Controller**: The function provides a clear snapshot of registration status. For a real-world system, integrating an automated notification system for waitlisted users when spots become available would be beneficial.
